# Generated by Django 4.0.3 on 2022-05-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
