# Generated by Django 4.0.3 on 2022-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_course_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_information',
            field=models.TextField(null=True),
        ),
    ]
