# Generated by Django 4.0.3 on 2022-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlineadmission', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
    ]
