# Generated by Django 4.0.3 on 2022-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcements', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='Circulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulars', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferences', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internships', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latestnews', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminars', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_events', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshops', models.TextField()),
                ('pic1', models.ImageField(null=True, upload_to='core/')),
                ('pic2', models.ImageField(null=True, upload_to='core/')),
            ],
        ),
        migrations.AddField(
            model_name='onlineadmission',
            name='pic2',
            field=models.ImageField(null=True, upload_to='core/'),
        ),
    ]
