# Generated by Django 4.0.3 on 2022-05-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcements_circulars_conferences_internships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='pic3',
            field=models.ImageField(null=True, upload_to='core/'),
        ),
        migrations.AddField(
            model_name='seminars',
            name='pic4',
            field=models.ImageField(null=True, upload_to='core/'),
        ),
    ]
