# Generated by Django 4.0.3 on 2022-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seminars_pic3_seminars_pic4'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='pic3',
            field=models.ImageField(null=True, upload_to='core/'),
        ),
        migrations.AddField(
            model_name='workshops',
            name='pic4',
            field=models.ImageField(null=True, upload_to='core/'),
        ),
    ]
