# Generated by Django 4.0.3 on 2022-05-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workshops_pic3_workshops_pic4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingevents',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='upcomingevents',
            name='pic2',
        ),
    ]
