# Generated by Django 4.0.3 on 2022-05-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_upcomingevents_pic1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internships',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='internships',
            name='pic2',
        ),
    ]
