# Generated by Django 4.0.3 on 2022-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_internships_pic1_remove_internships_pic2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulars',
            name='circulars',
        ),
        migrations.RemoveField(
            model_name='circulars',
            name='pic2',
        ),
    ]
