# Generated by Django 4.0.3 on 2022-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_course_student_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
