# Generated by Django 4.0.3 on 2022-06-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('aadhar', models.ImageField(upload_to='certificates/')),
                ('ssc_memo', models.ImageField(upload_to='certificates/')),
                ('ssc_bonafide', models.ImageField(upload_to='certificates/')),
                ('inter_memo', models.ImageField(upload_to='certificates/')),
                ('inter_bonafide', models.ImageField(upload_to='certificates/')),
                ('transfer_certifcate', models.ImageField(upload_to='certificates/')),
                ('caste_certificate', models.ImageField(upload_to='certificates/')),
                ('income_certificate', models.ImageField(upload_to='certificates/')),
                ('gap_certificate', models.ImageField(blank=True, upload_to='certificates/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
