# Generated by Django 4.0.3 on 2022-06-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentcertificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcertificates',
            old_name='transfer_certifcate',
            new_name='transfer_certificate',
        ),
    ]
