# Generated by Django 4.0.3 on 2022-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_transfer_certifcate_studentcertificates_transfer_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcertificates',
            name='permanent_address',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
