# Generated by Django 4.0.3 on 2022-06-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentcertificates_gap_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_status',
        ),
    ]
