# Generated by Django 4.0.3 on 2022-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcertificates',
            name='certificates_uploaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
