# Generated by Django 4.0.3 on 2022-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentcertificates_certificates_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcertificates',
            name='certificates_uploaded',
        ),
        migrations.AddField(
            model_name='student',
            name='certificates_uploaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
